In [7]:
import numpy as np
import pandas as pd
import math

In [9]:
nfa = pd.read_csv("NFA 2018.csv")

In [10]:
nfa.head()

,country,ISO alpha-3 code,UN_region,UN_subregion,year,record,crop_land,grazing_land,forest_land,fishing_ground,built_up_land,carbon,total,Percapita GDP (2010 USD),population
0,Armenia,ARM,Asia,Western Asia,1992,BiocapPerCap,1.611286e-01,0.135023,0.083836,0.013718,0.033669,0.000000e+00,4.273741e-01,949.033,3449000
1,Armenia,ARM,Asia,Western Asia,1992,BiocapTotGHA,5.558130e+05,465763.337400,289190.662300,47320.224590,116139.598200,0.000000e+00,1.474227e+06,949.033,3449000
2,Armenia,ARM,Asia,Western Asia,1992,EFConsPerCap,3.909225e-01,0.189137,0.000001,0.004138,0.033669,1.112225e+00,1.730092e+00,949.033,3449000
3,Armenia,ARM,Asia,Western Asia,1992,EFConsTotGHA,1.348487e+06,652429.066600,4.327841,14272.803690,116139.598200,3.836620e+06,5.967954e+06,949.033,3449000
4,Armenia,ARM,Asia,Western Asia,1992,EFExportsPerCap,1.124910e-03,0.002283,0.000000,0.000438,0.000000,4.819043e-02,5.203676e-02,949.033,3449000

In [11]:
nfa.UN_subregion.unique() ## list all unique categorical values in a column

array(['Western Asia', 'Southern Asia', 'Southern Europe',
       'Northern Africa', 'Middle Africa', 'Caribbean', 'South America',
       'Australia and New Zealand', 'Western Europe', 'North America',
       'Southern Africa', 'Central America', 'South-Eastern Asia',
       'Eastern Europe', 'Eastern Africa', 'Western Africa', 'Polynesia',
       'Northern Europe', 'Melanesia', 'Micronesia', 'Central Asia',
       'Eastern Asia', 'World'], dtype=object)

### subset based on row values

In [12]:
seac=nfa[nfa.UN_subregion == 'South-Eastern Asia']

In [14]:
seac.head()

,country,ISO alpha-3 code,UN_region,UN_subregion,year,record,crop_land,grazing_land,forest_land,fishing_ground,built_up_land,carbon,total,Percapita GDP (2010 USD),population
8900,Brunei Darussalam,BRN,Asia,South-Eastern Asia,1981,BiocapPerCap,0.026655,0.041847,3.492192,2.689280,0.024689,0.000000,6.274663e+00,46156.2,199000
8901,Brunei Darussalam,BRN,Asia,South-Eastern Asia,1981,BiocapTotGHA,5307.942727,8333.321310,695421.070600,535532.457100,4916.415726,0.000000,1.249511e+06,46156.2,199000
8902,Brunei Darussalam,BRN,Asia,South-Eastern Asia,1981,EFConsPerCap,0.514932,0.409487,0.840100,0.179163,0.024689,1.127578,3.095950e+00,46156.2,199000
8903,Brunei Darussalam,BRN,Asia,South-Eastern Asia,1981,EFConsTotGHA,102541.593800,81543.661670,167294.119500,35677.892910,4916.415726,224541.376700,6.165151e+05,46156.2,199000
8904,Brunei Darussalam,BRN,Asia,South-Eastern Asia,1981,EFExportsPerCap,0.009404,0.017047,0.001801,0.003619,0.000000,4.713569,4.745440e+00,46156.2,199000

### subset on basis of row numerical values

In [15]:
seac_fl=seac[seac.forest_land >= 5] ## isolate forest area>=5

In [16]:
seac_fl.head()

,country,ISO alpha-3 code,UN_region,UN_subregion,year,record,crop_land,grazing_land,forest_land,fishing_ground,built_up_land,carbon,total,Percapita GDP (2010 USD),population
8901,Brunei Darussalam,BRN,Asia,South-Eastern Asia,1981,BiocapTotGHA,5307.942727,8333.321310,695421.07060,535532.457100,4916.415726,0.0000,1.249511e+06,46156.2,199000
8903,Brunei Darussalam,BRN,Asia,South-Eastern Asia,1981,EFConsTotGHA,102541.593800,81543.661670,167294.11950,35677.892910,4916.415726,224541.3767,6.165151e+05,46156.2,199000
8905,Brunei Darussalam,BRN,Asia,South-Eastern Asia,1981,EFExportsTotGHA,1872.632945,3394.765946,358.56559,720.691864,0.000000,938641.3032,9.449880e+05,46156.2,199000
8907,Brunei Darussalam,BRN,Asia,South-Eastern Asia,1981,EFImportsTotGHA,99106.284060,76605.106300,19136.76642,33348.131510,0.000000,271898.9650,5.000953e+05,46156.2,199000
8909,Brunei Darussalam,BRN,Asia,South-Eastern Asia,1981,EFProdTotGHA,5307.942727,8333.321310,148515.91860,3050.453270,4916.415726,891283.7149,1.061408e+06,46156.2,199000

### subset based on list

In [17]:
years = [1990, 2000, 2005] ## list of years

In [19]:

seac.year.isin(years)

8900     False
8901     False
8902     False
8903     False
8904     False
8905     False
8906     False
8907     False
8908     False
8909     False
8910     False
8911     False
8912     False
8913     False
8914     False
8915     False
8916     False
8917     False
8918     False
8919     False
8920     False
8921     False
8922     False
8923     False
8924     False
8925     False
8926     False
8927     False
8928     False
8929     False
         ...
81910    False
81911    False
81912    False
81913    False
81914    False
81915    False
81916    False
81917    False
81918    False
81919    False
81920    False
81921    False
81922    False
81923    False
81924    False
81925    False
81926    False
81927    False
81928    False
81929    False
81930    False
81931    False
81932    False
81933    False
81934    False
81935    False
81936    False
81937    False
81938    False
81939    False
Name: year, Length: 5620, dtype: bool

In [20]:
seac_y = seac[seac.year.isin(years)]

In [21]:
seac_y.head()

,country,ISO alpha-3 code,UN_region,UN_subregion,year,record,crop_land,grazing_land,forest_land,fishing_ground,built_up_land,carbon,total,Percapita GDP (2010 USD),population
8990,Brunei Darussalam,BRN,Asia,South-Eastern Asia,1990,BiocapPerCap,0.017527,0.026257,2.732189,2.024860,0.027928,0.000000,4.828761e+00,37071.7,257000
8991,Brunei Darussalam,BRN,Asia,South-Eastern Asia,1990,BiocapTotGHA,4503.259637,6746.463581,702005.965100,520265.582100,7175.771633,0.000000,1.240697e+06,37071.7,257000
8992,Brunei Darussalam,BRN,Asia,South-Eastern Asia,1990,EFConsPerCap,0.580524,0.415528,0.612143,0.143426,0.027928,2.252388,4.031937e+00,37071.7,257000
8993,Brunei Darussalam,BRN,Asia,South-Eastern Asia,1990,EFConsTotGHA,149159.182100,106765.413600,157283.389300,36851.703370,7175.771633,578726.280700,1.035962e+06,37071.7,257000
8994,Brunei Darussalam,BRN,Asia,South-Eastern Asia,1990,EFExportsPerCap,0.021696,0.009066,0.000554,0.010032,0.000000,3.825185,3.866532e+00,37071.7,257000

### Select Rows of Pandas Dataframe Based on Values NOT in a list

In [22]:
nfa.UN_region.unique()

array(['Asia', 'Europe', 'Africa', 'Latin America and the Caribbean',
       'Oceania', 'North America', 'World'], dtype=object)

In [23]:
continents=['Africa', 'Latin America and the Caribbean',
       'Oceania', 'North America', 'World'] ##we want to leave these out

In [30]:
nfa_cont = nfa[~nfa.UN_region.isin(continents)] ## check if members of the
##column UN_region are in the list
## we want to only retain data for Asia & africa

In [31]:
nfa_cont.head()

,country,ISO alpha-3 code,UN_region,UN_subregion,year,record,crop_land,grazing_land,forest_land,fishing_ground,built_up_land,carbon,total,Percapita GDP (2010 USD),population
0,Armenia,ARM,Asia,Western Asia,1992,BiocapPerCap,1.611286e-01,0.135023,0.083836,0.013718,0.033669,0.000000e+00,4.273741e-01,949.033,3449000
1,Armenia,ARM,Asia,Western Asia,1992,BiocapTotGHA,5.558130e+05,465763.337400,289190.662300,47320.224590,116139.598200,0.000000e+00,1.474227e+06,949.033,3449000
2,Armenia,ARM,Asia,Western Asia,1992,EFConsPerCap,3.909225e-01,0.189137,0.000001,0.004138,0.033669,1.112225e+00,1.730092e+00,949.033,3449000
3,Armenia,ARM,Asia,Western Asia,1992,EFConsTotGHA,1.348487e+06,652429.066600,4.327841,14272.803690,116139.598200,3.836620e+06,5.967954e+06,949.033,3449000
4,Armenia,ARM,Asia,Western Asia,1992,EFExportsPerCap,1.124910e-03,0.002283,0.000000,0.000438,0.000000,4.819043e-02,5.203676e-02,949.033,3449000

In [38]:
nfa_cont2 = nfa[nfa.UN_region.isin(continents)]

In [39]:
nfa_cont2.head()

,country,ISO alpha-3 code,UN_region,UN_subregion,year,record,crop_land,grazing_land,forest_land,fishing_ground,built_up_land,carbon,total,Percapita GDP (2010 USD),population
1310,Algeria,DZA,Africa,Northern Africa,1961,BiocapPerCap,NaN,NaN,NaN,NaN,NaN,NaN,1.445786e+00,2078.22,11405000
1311,Algeria,DZA,Africa,Northern Africa,1961,BiocapTotGHA,NaN,NaN,NaN,NaN,NaN,NaN,1.648904e+07,2078.22,11405000
1312,Algeria,DZA,Africa,Northern Africa,1961,EFConsPerCap,NaN,NaN,NaN,NaN,NaN,NaN,7.360894e-01,2078.22,11405000
1313,Algeria,DZA,Africa,Northern Africa,1961,EFConsTotGHA,NaN,NaN,NaN,NaN,NaN,NaN,8.395027e+06,2078.22,11405000
1314,Algeria,DZA,Africa,Northern Africa,1961,EFExportsPerCap,NaN,NaN,NaN,NaN,NaN,NaN,1.472014e-01,2078.22,11405000

### multiple conditions

In [32]:
years2 = [1995, 2000, 2005] ## list of years

In [33]:
continents=['Africa', 'Latin America and the Caribbean',
       'Oceania', 'North America', 'World']

In [36]:
m=nfa[~nfa.UN_region.isin(continents) & 
           nfa.year.isin(years2)]

In [37]:
m.head()

,country,ISO alpha-3 code,UN_region,UN_subregion,year,record,crop_land,grazing_land,forest_land,fishing_ground,built_up_land,carbon,total,Percapita GDP (2010 USD),population
30,Armenia,ARM,Asia,Western Asia,1995,BiocapPerCap,1.649966e-01,0.156922,0.089827,0.014604,0.031497,0.000000e+00,4.578459e-01,1043.54,3223000
31,Armenia,ARM,Asia,Western Asia,1995,BiocapTotGHA,5.318121e+05,505784.775600,289527.235600,47069.840160,101521.311600,0.000000e+00,1.475715e+06,1043.54,3223000
32,Armenia,ARM,Asia,Western Asia,1995,EFConsPerCap,3.803621e-01,0.196215,0.000017,0.003926,0.031497,4.161801e-01,1.028198e+00,1043.54,3223000
33,Armenia,ARM,Asia,Western Asia,1995,EFConsTotGHA,1.225972e+06,632435.037500,54.385847,12654.898940,101521.311600,1.341419e+06,3.314057e+06,1043.54,3223000
34,Armenia,ARM,Asia,Western Asia,1995,EFExportsPerCap,1.640147e-03,0.006396,0.000009,0.000651,0.000000,4.614820e-02,5.484422e-02,1043.54,3223000